import 'dart:math';

/// A thoughtful question grouped into a theme for daily journaling.
class ReflectionPrompt {
  const ReflectionPrompt({required this.text, required this.category});

  final String text;
  final String category;
}

class PromptService {
  PromptService._();

  static final PromptService instance = PromptService._();
  final Random _random = Random();

  static const List<ReflectionPrompt> prompts = [
    ReflectionPrompt(text: 'What is one small thing that brought you comfort today?', category: 'Gratitude'),
    ReflectionPrompt(text: 'Who made your day a little better, and how?', category: 'Gratitude'),
    ReflectionPrompt(text: 'What part of your life do you sometimes take for granted?', category: 'Gratitude'),
    ReflectionPrompt(text: 'What ordinary moment from this week would you like to remember?', category: 'Gratitude'),
    ReflectionPrompt(text: 'What strength in yourself are you grateful to have developed?', category: 'Gratitude'),
    ReflectionPrompt(text: 'What is something beautiful you noticed recently that you might otherwise have missed?', category: 'Mindfulness'),
    ReflectionPrompt(text: 'What feeling has been asking for your attention today?', category: 'Mindfulness'),
    ReflectionPrompt(text: 'When did you feel most present in the moment this week?', category: 'Mindfulness'),
    ReflectionPrompt(text: 'What can you let be unfinished for now?', category: 'Mindfulness'),
    ReflectionPrompt(text: 'What would a gentler pace look like for you tomorrow?', category: 'Mindfulness'),
    ReflectionPrompt(text: 'What did a recent challenge teach you about yourself?', category: 'Personal Growth'),
    ReflectionPrompt(text: 'Which belief about yourself are you ready to question?', category: 'Personal Growth'),
    ReflectionPrompt(text: 'What is one brave, small step you could take toward something meaningful?', category: 'Personal Growth'),
    ReflectionPrompt(text: 'Where have you grown in a way that your past self would appreciate?', category: 'Personal Growth'),
    ReflectionPrompt(text: 'What mistake could you treat as information rather than a verdict?', category: 'Personal Growth'),
    ReflectionPrompt(text: 'What does success mean to you when nobody else is watching?', category: 'Personal Growth'),
    ReflectionPrompt(text: 'What boundary would help you protect your time or energy?', category: 'Personal Growth'),
    ReflectionPrompt(text: 'What would you try if you trusted yourself to learn along the way?', category: 'Personal Growth'),
    ReflectionPrompt(text: 'What conversation has stayed with you, and why?', category: 'Relationships'),
    ReflectionPrompt(text: 'Who might need to hear appreciation from you?', category: 'Relationships'),
    ReflectionPrompt(text: 'When do you feel most understood by another person?', category: 'Relationships'),
    ReflectionPrompt(text: 'What is one way you could listen more generously this week?', category: 'Relationships'),
    ReflectionPrompt(text: 'Which relationship deserves more intentional time from you?', category: 'Relationships'),
    ReflectionPrompt(text: 'What do you wish people understood about you more easily?', category: 'Relationships'),
    ReflectionPrompt(text: 'What is something you need to forgive yourself for, even if slowly?', category: 'Self-Compassion'),
    ReflectionPrompt(text: 'How would you speak to a friend facing the same worry you have?', category: 'Self-Compassion'),
    ReflectionPrompt(text: 'What expectation could you release to make room for peace?', category: 'Self-Compassion'),
    ReflectionPrompt(text: 'What have you handled lately that deserves more credit?', category: 'Self-Compassion'),
    ReflectionPrompt(text: 'What does rest look like when you stop trying to earn it?', category: 'Self-Compassion'),
    ReflectionPrompt(text: 'What is taking up the most space in your mind right now?', category: 'Clarity'),
    ReflectionPrompt(text: 'What matters most to you in this season of life?', category: 'Clarity'),
    ReflectionPrompt(text: 'What is one thing you can influence today, and one thing you can release?', category: 'Clarity'),
    ReflectionPrompt(text: 'What would make tomorrow feel meaningful, even if it is imperfect?', category: 'Clarity'),
    ReflectionPrompt(text: 'Which commitment still reflects your values, and which may need revisiting?', category: 'Clarity'),
    ReflectionPrompt(text: 'What are you curious to explore simply because it interests you?', category: 'Possibility'),
    ReflectionPrompt(text: 'If you had an extra hour with no obligations, how would you use it?', category: 'Possibility'),
    ReflectionPrompt(text: 'What possibility feels exciting even though it is not fully mapped out?', category: 'Possibility'),
    ReflectionPrompt(text: 'What would you like your future self to thank you for starting today?', category: 'Possibility'),
    ReflectionPrompt(text: 'What is one experience you want to make more room for this month?', category: 'Possibility'),
    ReflectionPrompt(text: 'What did today reveal about what you need more—or less—of?', category: 'Daily Review'),
    ReflectionPrompt(text: 'What is one moment from today you want to carry into tomorrow?', category: 'Daily Review'),
    ReflectionPrompt(text: "What support have you received that you have not fully acknowledged?", category: "Gratitude"),
    ReflectionPrompt(text: "Which simple pleasure would you miss most if it disappeared from your routine?", category: "Gratitude"),
    ReflectionPrompt(text: "What did someone teach you through their example rather than their words?", category: "Gratitude"),
    ReflectionPrompt(text: "What part of your daily life makes you feel safe or grounded?", category: "Gratitude"),
    ReflectionPrompt(text: "What is something your body helped you do today that you appreciate?", category: "Gratitude"),
    ReflectionPrompt(text: "Where in your body do you notice stress, and what might it be asking for?", category: "Mindfulness"),
    ReflectionPrompt(text: "What changes when you give a difficult feeling room without judging it?", category: "Mindfulness"),
    ReflectionPrompt(text: "Which part of your day passed by while your attention was somewhere else?", category: "Mindfulness"),
    ReflectionPrompt(text: "What can you notice with your senses right now that you usually overlook?", category: "Mindfulness"),
    ReflectionPrompt(text: "What would it mean to meet today exactly as it is?", category: "Mindfulness"),
    ReflectionPrompt(text: "What pattern are you beginning to recognize in your choices?", category: "Personal Growth"),
    ReflectionPrompt(text: "Which uncomfortable truth might help you grow if you faced it gently?", category: "Personal Growth"),
    ReflectionPrompt(text: "What skill or quality are you willing to practice imperfectly?", category: "Personal Growth"),
    ReflectionPrompt(text: "What feedback have you received that is worth considering without accepting blindly?", category: "Personal Growth"),
    ReflectionPrompt(text: "What would progress look like if you measured it by consistency instead of speed?", category: "Personal Growth"),
    ReflectionPrompt(text: "What old version of yourself are you still trying to prove something to?", category: "Personal Growth"),
    ReflectionPrompt(text: "Which fear has been making decisions on your behalf?", category: "Personal Growth"),
    ReflectionPrompt(text: "When did someone make you feel seen, and what did they do?", category: "Relationships"),
    ReflectionPrompt(text: "What assumption about another person could you check instead of carrying?", category: "Relationships"),
    ReflectionPrompt(text: "How can you show care while still respecting your own limits?", category: "Relationships"),
    ReflectionPrompt(text: "Which relationship helps you become more honest with yourself?", category: "Relationships"),
    ReflectionPrompt(text: "What apology, clarification, or appreciation might bring more understanding?", category: "Relationships"),
    ReflectionPrompt(text: "When a disagreement happens, what do you most need the other person to understand?", category: "Relationships"),
    ReflectionPrompt(text: "What would you allow yourself to do if you did not need to justify resting?", category: "Self-Compassion"),
    ReflectionPrompt(text: "Which part of your story deserves kindness rather than criticism?", category: "Self-Compassion"),
    ReflectionPrompt(text: "What are you demanding of yourself that you would never demand of someone you love?", category: "Self-Compassion"),
    ReflectionPrompt(text: "How can you make room for being both capable and still learning?", category: "Self-Compassion"),
    ReflectionPrompt(text: "What would forgiving yourself look like in one small, practical action?", category: "Self-Compassion"),
    ReflectionPrompt(text: "What is important but has been crowded out by what feels urgent?", category: "Clarity"),
    ReflectionPrompt(text: "Which decision becomes clearer when you name the values behind it?", category: "Clarity"),
    ReflectionPrompt(text: "What are you carrying because you have not decided whether it is still yours to carry?", category: "Clarity"),
    ReflectionPrompt(text: "What would you choose if you focused on what matters rather than what impresses?", category: "Clarity"),
    ReflectionPrompt(text: "What deserves a clear yes from you, and what deserves a respectful no?", category: "Clarity"),
    ReflectionPrompt(text: "What would you explore if you gave yourself permission to be a beginner?", category: "Possibility"),
    ReflectionPrompt(text: "What small change could make your ordinary days feel more like your own?", category: "Possibility"),
    ReflectionPrompt(text: "What dream have you made smaller to avoid disappointment?", category: "Possibility"),
    ReflectionPrompt(text: "What new experience might challenge an assumption you hold about yourself?", category: "Possibility"),
    ReflectionPrompt(text: "What could become possible if you asked for help sooner?", category: "Possibility"),
    ReflectionPrompt(text: "What moment today showed you what you truly value?", category: "Daily Review"),
    ReflectionPrompt(text: "What drained your energy today, and what restored even a little of it?", category: "Daily Review"),
    ReflectionPrompt(text: "What did you do today that aligned with the person you want to become?", category: "Daily Review"),
    ReflectionPrompt(text: "What would you like to do differently tomorrow, without turning it into self-criticism?", category: "Daily Review"),
    ReflectionPrompt(text: "What is one unfinished thing you can consciously set down for tonight?", category: "Daily Review"),
    ReflectionPrompt(text: "What principle do you want your choices to reflect even when it is inconvenient?", category: "Purpose & Values"),
    ReflectionPrompt(text: "What kind of contribution feels meaningful to you at this stage of life?", category: "Purpose & Values"),
    ReflectionPrompt(text: "When have you felt most aligned with your values recently?", category: "Purpose & Values"),
    ReflectionPrompt(text: "What would you want people to feel after spending time with you?", category: "Purpose & Values"),
    ReflectionPrompt(text: "Which success would feel empty if it cost you your peace?", category: "Purpose & Values"),
    ReflectionPrompt(text: "What has helped you endure a season you once thought you could not handle?", category: "Resilience"),
    ReflectionPrompt(text: "What resource, person, or routine could support you through a current challenge?", category: "Resilience"),
    ReflectionPrompt(text: "What is one thing you know now that you did not know during a past hardship?", category: "Resilience"),
    ReflectionPrompt(text: "How can you distinguish a temporary setback from a story you are telling about yourself?", category: "Resilience"),
    ReflectionPrompt(text: "What does asking for support look like before you reach your limit?", category: "Resilience"),
    ReflectionPrompt(text: "What question have you been curious about but not made time to explore?", category: "Creativity & Curiosity"),
    ReflectionPrompt(text: "What would you create if the result did not need to be useful or impressive?", category: "Creativity & Curiosity"),
    ReflectionPrompt(text: "What idea from a different field could change how you approach a current problem?", category: "Creativity & Curiosity"),
    ReflectionPrompt(text: "Where could you replace certainty with a little more curiosity?", category: "Creativity & Curiosity"),
    ReflectionPrompt(text: "What activity makes you lose track of time in a healthy, satisfying way?", category: "Creativity & Curiosity"),
    ReflectionPrompt(text: "What helps you feel renewed without requiring you to achieve anything first?", category: "Rest & Renewal"),
      ReflectionPrompt(text: "What kindness did you receive today that you want to remember?", category: "Gratitude"),
    ReflectionPrompt(text: "What place makes you feel grateful simply by being there?", category: "Gratitude"),
    ReflectionPrompt(text: "What is one resource in your life you often overlook?", category: "Gratitude"),
    ReflectionPrompt(text: "What did you notice today when you slowed down?", category: "Mindfulness"),
    ReflectionPrompt(text: "Which sound, sight, or texture helped you feel present?", category: "Mindfulness"),
    ReflectionPrompt(text: "What thought can you observe without needing to solve it?", category: "Mindfulness"),
    ReflectionPrompt(text: "What habit would make the person you want to become more likely?", category: "Personal Growth"),
    ReflectionPrompt(text: "What is one lesson you keep learning in different forms?", category: "Personal Growth"),
    ReflectionPrompt(text: "Where could you replace perfection with practice?", category: "Personal Growth"),
    ReflectionPrompt(text: "Who deserves a little more patience from you?", category: "Relationships"),
    ReflectionPrompt(text: "What relationship feels easier when you are honest about your needs?", category: "Relationships"),
    ReflectionPrompt(text: "What is one thoughtful message you could send today?", category: "Relationships"),
    ReflectionPrompt(text: "What would you stop blaming yourself for if you knew you had done your best?", category: "Self-Compassion"),
    ReflectionPrompt(text: "Where can you give yourself permission to begin again?", category: "Self-Compassion"),
    ReflectionPrompt(text: "What part of today deserves compassion rather than analysis?", category: "Self-Compassion"),
    ReflectionPrompt(text: "What decision are you postponing, and what information would help?", category: "Clarity"),
    ReflectionPrompt(text: "What is the simplest next step hiding inside a complicated problem?", category: "Clarity"),
    ReflectionPrompt(text: "What can you remove from your schedule to protect what matters?", category: "Clarity"),
    ReflectionPrompt(text: "What idea would you explore if you had nothing to prove?", category: "Possibility"),
    ReflectionPrompt(text: "What opportunity could come from an unexpected change?", category: "Possibility"),
    ReflectionPrompt(text: "What would you like to learn just for the joy of learning?", category: "Possibility"),
    ReflectionPrompt(text: "What did you do today that made tomorrow easier?", category: "Daily Review"),
    ReflectionPrompt(text: "What surprised you about yourself today?", category: "Daily Review"),
    ReflectionPrompt(text: "Which moment would you replay because it mattered?", category: "Daily Review"),
    ReflectionPrompt(text: "What value do you want to practice more visibly this week?", category: "Purpose & Values"),
    ReflectionPrompt(text: "What would a meaningful day look like without external applause?", category: "Purpose & Values"),
    ReflectionPrompt(text: "Which choice recently felt deeply like yourself?", category: "Purpose & Values"),
    ReflectionPrompt(text: "What helped you keep going when motivation was low?", category: "Resilience"),
    ReflectionPrompt(text: "What evidence reminds you that difficult seasons can change?", category: "Resilience"),
    ReflectionPrompt(text: "What strength have you built because life asked you to?", category: "Resilience"),
    ReflectionPrompt(text: "What ordinary problem could you solve in a completely different way?", category: "Creativity & Curiosity"),
    ReflectionPrompt(text: "What question would you ask if you were not afraid of sounding naive?", category: "Creativity & Curiosity"),
    ReflectionPrompt(text: "What kind of rest would actually restore you today?", category: "Rest & Renewal"),
    ReflectionPrompt(text: "What can wait until tomorrow so tonight can feel lighter?", category: "Rest & Renewal"),
    ReflectionPrompt(text: "What simple ritual helps you return to yourself?", category: "Rest & Renewal"),
    ReflectionPrompt(text: "What do you hope your future self remembers about this season?", category: "Future Self"),
    ReflectionPrompt(text: "What small choice today could improve your life six months from now?", category: "Future Self"),
    ReflectionPrompt(text: "What would you like to have learned by this time next year?", category: "Future Self"),
      ReflectionPrompt(text: "What is one ordinary convenience today that you are glad exists?", category: "Gratitude"),
    ReflectionPrompt(text: "What changed when you gave your full attention to one simple task?", category: "Mindfulness"),
    ReflectionPrompt(text: "What would you practice if progress could be private?", category: "Personal Growth"),
    ReflectionPrompt(text: "What quality do you most appreciate in the people you trust?", category: "Relationships"),
    ReflectionPrompt(text: "What would it look like to be on your own side today?", category: "Self-Compassion"),
    ReflectionPrompt(text: "Which priority deserves your attention before anything else?", category: "Clarity"),
    ReflectionPrompt(text: "What small experiment could teach you something useful this week?", category: "Possibility"),
    ReflectionPrompt(text: "What did you learn from today that you want to carry forward?", category: "Daily Review"),
    ReflectionPrompt(text: "What do you want your time to say about what matters to you?", category: "Purpose & Values"),
    ReflectionPrompt(text: "What previous challenge proves you can adapt again?", category: "Resilience"),
    ReflectionPrompt(text: "What could you make if you gave yourself thirty uninterrupted minutes?", category: "Creativity & Curiosity"),
    ReflectionPrompt(text: "What would make tonight feel genuinely restorative?", category: "Rest & Renewal"),
  ];

  /// Returns a prompt that is stable for the whole local calendar day.
  ReflectionPrompt getPromptOfDay({DateTime? date}) {
    final now = date ?? DateTime.now();
    final day = DateTime(now.year, now.month, now.day);
    final epoch = DateTime(2024, 1, 1);
    final dayIndex = day.difference(epoch).inDays.abs();
    return prompts[dayIndex % prompts.length];
  }

  /// Returns a randomly selected reflective prompt.
  ReflectionPrompt getRandomPrompt() => prompts[_random.nextInt(prompts.length)];
}
