
import 'package:flutter/services.dart';

/// Android integration bridge for NOVA.
///
/// The Dart app remains platform-safe until the Android platform folder is
/// generated by Flutter. Native features can then be connected through these
/// channel names without changing the feature UI.
class NovaAndroidService {
  static const _channel = MethodChannel('nova_notes/android');

  Future<void> openQuickNote() async {
    try {
      await _channel.invokeMethod<void>('openQuickNote');
    } on MissingPluginException {
      // Native integration is not generated yet. Safe no-op for other platforms.
    }
  }

  Future<void> shareText({
    required String title,
    required String text,
  }) async {
    try {
      await _channel.invokeMethod<void>('shareText', {
        'title': title,
        'text': text,
      });
    } on MissingPluginException {
      // Native integration will be wired after Android project generation.
    }
  }
}
